version: 0.2
phases:
  build:
    commands:
      - |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h4u2q3r3
        docker build -t maestro .
        docker tag maestro:latest public.ecr.aws/h4u2q3r3/maestro:latest
        docker push public.ecr.aws/h4u2q3r3/maestro:latest
