name: Create a release pull-request
on:
  push:
    branches:
      - main
jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: Release pull-request
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Create release-pr
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: main
          head: ${GITHUB_REF##*/}
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: a,b,c
          assign: true
