on:
  release:
      types:
          - published
jobs:
    register:
        runs-on:
            - ubuntu-latest
        steps:
          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v1
            with:
              aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.SECRET_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}          
            
          - name: Authenticate Docker
            run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h4u2q3r3
          
          - name: Build Docker AMI
            run: docker build -t aws-codebuild-cloud-native-buildpacks .
